In [59]:
import pandas as pd
from textblob import TextBlob

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix

In [60]:
file_path = "review_data.csv"

df = pd.read_csv(file_path, encoding="latin1")

print("Columns in dataset:")
print(df.columns)

df.head()

Columns in dataset:
Index(['title', 'rating', 'review'], dtype='object')

,title,rating,review
0,Perfectly matched,5,"Perfectly matched , luxurious coverage"
1,Foundation,5,Thorough quiz to ensure the customer receives ...
2,Excellent helpful customer service,5,Excellent helpful customer service Thank you
3,How did I survive without this awesome,5,How did I survive without this awesome make up...
4,Perfect thank you,5,Perfect thank you

In [61]:
review_column = "review"
true_label_column = "rating"

In [62]:
def get_polarity(text):
    blob = TextBlob(str(text))
    return round(blob.sentiment.polarity, 2)

In [63]:
df["polarity_score"] = df[review_column].apply(get_polarity)

df.head()

,title,rating,review,polarity_score
0,Perfectly matched,5,"Perfectly matched , luxurious coverage",1.0
1,Foundation,5,Thorough quiz to ensure the customer receives ...,1.0
2,Excellent helpful customer service,5,Excellent helpful customer service Thank you,1.0
3,How did I survive without this awesome,5,How did I survive without this awesome make up...,1.0
4,Perfect thank you,5,Perfect thank you,1.0

In [64]:
def get_sentiment_label(score):
    
    if score > 0:
        return "positive"
    
    elif score < 0:
        return "negative"
    
    else:
        return "neutral"


df["predicted_sentiment"] = df["polarity_score"].apply(get_sentiment_label)

df.head()

,title,rating,review,polarity_score,predicted_sentiment
0,Perfectly matched,5,"Perfectly matched , luxurious coverage",1.0,positive
1,Foundation,5,Thorough quiz to ensure the customer receives ...,1.0,positive
2,Excellent helpful customer service,5,Excellent helpful customer service Thank you,1.0,positive
3,How did I survive without this awesome,5,How did I survive without this awesome make up...,1.0,positive
4,Perfect thank you,5,Perfect thank you,1.0,positive

In [65]:
def convert_rating_to_sentiment(rating):

    if rating >= 4:
        return "positive"

    elif rating <= 2:
        return "negative"

    else:
        return "neutral"

In [66]:
df["true_sentiment"] = df["rating"].apply(convert_rating_to_sentiment)

In [67]:
y_true = df["true_sentiment"]
y_pred = df["predicted_sentiment"]

In [68]:
accuracy = accuracy_score(y_true, y_pred)

precision = precision_score(y_true, y_pred, average="weighted")

recall = recall_score(y_true, y_pred, average="weighted")

f1 = f1_score(y_true, y_pred, average="weighted")

print("Model Performance Metrics\n")

print("Accuracy:", round(accuracy, 3))
print("Precision:", round(precision, 3))
print("Recall:", round(recall, 3))
print("F1 Score:", round(f1, 3))

Model Performance Metrics

Accuracy: 0.788
Precision: 0.804
Recall: 0.788
F1 Score: 0.778